repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-lint
    - id: go-imports
    - id: go-cyclo
    - id: validate-toml
    - id: no-go-testing
    - id: golangci-lint
    - id: go-critic
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
  - id: check-merge-conflict
  - id: end-of-file-fixer

- repo: local
  hooks:
  - id: dependency-check
    name: OWASP Dependency Check
    entry: dependency-check --out . --scan . --enableExperimental --failOnCVSS 0 --suppression dependency-suppressions.xml
    pass_filenames: false
    language: system
    files: .*\.mod$

- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.32.2
  hooks:
    - id: commitizen
      stages: [commit-msg]

- repo: https://github.com/milin/giticket
  rev: v1.4
  hooks:
  - id:  giticket
    args: ['--regex=[A-Z]{2,4}-[0-9]+', '--format=[{ticket}] {commit_msg}', '--mode=regex_match']
